version: '3'

services:
  postgres-hyproof-api:
    image: postgres:16.1-alpine
    container_name: postgres-hyproof-api
    ports:
      - 5432:5432
    volumes:
      - hyproof-api-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dscp-hyproof-api

  dscp-hyproof-api:
    image: digicatapult/dscp-hyproof-api:latest
    container_name: hyproof-api
    command: /bin/sh -c "
      sleep 40 &&
      npx knex migrate:latest --knexfile build/lib/db/knexfile.ts &&
      npx @digicatapult/dscp-process-management@latest create -h node -p 9944 -u //Alice -f ./processFlows.json &&
      npm start"
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - LOG_LEVEL=debug
      - API_HOST=dscp-node
      - DB_HOST=postgres-hyproof-api
      - DB_PORT=5432
      - DB_NAME=dscp-hyproof-api
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - IDENTITY_SERVICE_HOST=identity-service
      - IDENTITY_SERVICE_PORT=3002
      - NODE_HOST=node
      - NODE_PORT=9944
      - USER_URI=//Alice
      - IPFS_HOST=ipfs
      - IPFS_PORT=5001

  postgres-identity-service:
    image: postgres:16.1-alpine
    container_name: postgres-identity
    ports:
      - 5433:5432
    volumes:
      - identity-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dscp-identity-service

  dscp-identity-service:
    image: digicatapult/dscp-identity-service:latest
    container_name: identity-service
    command: /bin/sh -c "
      sleep 30 &&
      npx knex migrate:latest &&
      node app/index.js"
    ports:
      - 3002:3002
    environment:
      - PORT=3002
      - API_HOST=dscp-node
      - DB_HOST=postgres-identity-service
      - DB_PORT=5432
      - DB_NAME=dscp-identity-service
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - SELF_ADDRESS=5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY
      - AUTH_TYPE=${AUTH_TYPE:-NONE}

  dscp-node:
    image: digicatapult/dscp-node:latest
    container_name: node
    command: --base-path /data/
      --dev
      --unsafe-ws-external
      --unsafe-rpc-external
      --ws-max-connections 512
      --rpc-cors all
    ports:
      - 30333:30333
      - 9944:9944
      - 9933:9933
    restart: on-failure

  ipfs:
    image: ipfs/go-ipfs:v0.25.0
    container_name: ipfs
    environment:
      - |
        IPFS_SWARM_KEY=/key/swarm/psk/1.0.0/
        /base16/
        0000000000000000000000000000000000000000000000000000000000000000
    ports:
      - 4001:4001
      - 8080:8080
      - 5001:5001

volumes:
  hyproof-api-storage:
  identity-storage:
