services:
  ##################################################################################
  ## Heidi the Hydrogen Producer ###################################################
  ##################################################################################

  hydrogen-producer-postgres-hyproof-api:
    image: postgres:16.1-alpine
    container_name: hydrogen-producer-postgres-hyproof-api
    depends_on:
      hydrogen-producer-node:
        condition: service_healthy
    volumes:
      - hydrogen-producer-hyproof-api-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sqnc-hyproof-api
    networks: ['hydrogen-producer']

  hydrogen-producer-hyproof-api:
    container_name: hydrogen-producer-hyproof-api
    image: digicatapult/sqnc-hyproof-api:latest
    command: /bin/sh -c "
      sleep 10 &&
      npx knex migrate:latest --knexfile build/lib/db/knexfile &&
      npx @digicatapult/sqnc-process-management@latest create -h hydrogen-producer-node -p 9944 -u //Alice -f ./processFlows.json &&
      npm start"
    environment:
      - PORT=8000
      - LOG_LEVEL=debug
      - NODE_HOST=hydrogen-producer-node
      - NODE_PORT=9944
      - DB_HOST=hydrogen-producer-postgres-hyproof-api
      - DB_PORT=5432
      - DB_NAME=sqnc-hyproof-api
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - IDENTITY_SERVICE_HOST=hydrogen-producer-identity
      - IDENTITY_SERVICE_PORT=9000
      - IPFS_HOST=hydrogen-producer-ipfs
      - IPFS_PORT=5001
      - USER_URI=//Alice
      - 'API_SWAGGER_BG_COLOR=#e4f2f3'
      - 'API_SWAGGER_TITLE=HyProof API - Heidi'
      - 'API_SWAGGER_HEADING=HyProof API - Heidi'
    ports:
      - 8000:8000
    depends_on:
      hydrogen-producer-node:
        condition: service_healthy
      hydrogen-producer-identity:
        condition: service_started
      hydrogen-producer-postgres-hyproof-api:
        condition: service_started
      hydrogen-producer-ipfs:
        condition: service_healthy
    restart: on-failure
    networks: ['hydrogen-producer']

  ##################################################################################
  ## Emma the Energy Owner #########################################################
  ##################################################################################

  energy-owner-postgres-hyproof-api:
    image: postgres:16.1-alpine
    container_name: energy-owner-postgres-hyproof-api
    depends_on:
      energy-owner-node:
        condition: service_healthy
    volumes:
      - energy-owner-hyproof-api-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sqnc-hyproof-api
    networks: ['energy-owner']

  energy-owner-hyproof-api:
    container_name: energy-owner-hyproof-api
    image: digicatapult/sqnc-hyproof-api:latest
    command: /bin/sh -c "
      sleep 10 &&
      npx knex migrate:latest --knexfile build/lib/db/knexfile &&
      npm start"
    environment:
      - PORT=8010
      - LOG_LEVEL=debug
      - NODE_HOST=energy-owner-node
      - NODE_PORT=9944
      - DB_HOST=energy-owner-postgres-hyproof-api
      - DB_PORT=5432
      - DB_NAME=sqnc-hyproof-api
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - IDENTITY_SERVICE_HOST=energy-owner-identity
      - IDENTITY_SERVICE_PORT=9010
      - IPFS_HOST=energy-owner-ipfs
      - IPFS_PORT=5001
      - USER_URI=//Bob
      - 'API_SWAGGER_BG_COLOR=#e7f6e6'
      - 'API_SWAGGER_TITLE=HyProof API - Emma'
      - 'API_SWAGGER_HEADING=HyProof API - Emma'
    ports:
      - 8010:8010
    depends_on:
      energy-owner-node:
        condition: service_healthy
      energy-owner-identity:
        condition: service_started
      energy-owner-postgres-hyproof-api:
        condition: service_started
      energy-owner-ipfs:
        condition: service_healthy
    restart: on-failure
    networks: ['energy-owner']

  ##################################################################################
  ## Reginald the Regulator ########################################################
  ##################################################################################

  regulator-postgres-hyproof-api:
    image: postgres:16.1-alpine
    container_name: regulator-postgres-hyproof-api
    depends_on:
      regulator-node:
        condition: service_healthy
    volumes:
      - regulator-hyproof-api-storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=sqnc-hyproof-api
    networks: ['regulator']

  regulator-hyproof-api:
    container_name: regulator-hyproof-api
    image: digicatapult/sqnc-hyproof-api:latest
    command: /bin/sh -c "
      sleep 10 &&
      npx knex migrate:latest --knexfile build/lib/db/knexfile &&
      npm start"
    environment:
      - PORT=8020
      - LOG_LEVEL=debug
      - NODE_HOST=regulator-node
      - NODE_PORT=9944
      - DB_HOST=regulator-postgres-hyproof-api
      - DB_PORT=5432
      - DB_NAME=sqnc-hyproof-api
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - IDENTITY_SERVICE_HOST=regulator-identity
      - IDENTITY_SERVICE_PORT=9020
      - IPFS_HOST=regulator-ipfs
      - IPFS_PORT=5001
      - USER_URI=//Charlie
      - 'API_SWAGGER_BG_COLOR=#f8dddd'
      - 'API_SWAGGER_TITLE=HyProof API - Reginald'
      - 'API_SWAGGER_HEADING=HyProof API - Reginald'
    ports:
      - 8020:8020
    depends_on:
      regulator-node:
        condition: service_healthy
      regulator-identity:
        condition: service_started
      regulator-postgres-hyproof-api:
        condition: service_started
      regulator-ipfs:
        condition: service_healthy
    restart: on-failure
    networks: ['regulator']

volumes:
  hydrogen-producer-hyproof-api-storage:
  energy-owner-hyproof-api-storage:
  regulator-hyproof-api-storage:
